Repository Kodeshack/Alexandria, pull requests merged in 2019-02, with the labels that each got.

#23 feat(routes): validate emails when creating a user
  routes/admin.go
Labels: enhancement

#30 refactor(config): use config struct instead passing around loose values
  .gitignore
  content/.gitkeep
  main.go
  models/config.go
  routes/admin.go
  routes/article.go
  routes/index.go
Labels: enhancement

#32 fix(article): add Content-Type to http header
  routes/article.go
Labels: bug

#33 feat(robots): add robots.txt
  routes/index.go
Labels: feature, good first issue

#35 fix(editor): fix the editor template
  view/templates/editor.html
Labels: bug

#37 feat(user): add user settings page
  main.go
  models/user.go
  routes/user.go
  view/templates/index.html
  view/templates/user.html
Labels: feature

#39 feat(input): trim most user input
  routes/admin.go
  routes/article.go
  routes/user.go
Labels: enhancement

#41 refactor(routes): improve routes
  main.go
  routes/admin.go
  routes/articles.go
  routes/index.go
  routes/login.go
  routes/logout.go
  routes/user.go
  view/templates/category.html
  view/templates/editor.html
  view/templates/index.html
Labels: enhancement

#43 feat(user): guarantee userIDs to be unique
  models/user.go
  routes/user.go
Labels: bug

#44 refactor(const): replace var with const
  models/user.go
Labels: enhancement

#46 feat(login): redirect to /login when no session is found
  routes/index.go
Labels: enhancement

#48 refactor(user): remove CreateUser struct as it's dead code
  models/user.go
Labels: enhancement
